### PR TITLE
Added `add` function

### PR DESCRIPTION
**Pull request by pjona**

### CODE REVIEW

**Comment by RamonSmit** [comment]
You're working quite hard on this one 👍

**Comment by pjona** [comment]
@RamonSmit can you make new release on GitHub?

**Comment by pjona** [comment]
@RamonSmit I also thinking about adding ESLint, and few events.

**Comment by RamonSmit** [comment]
New release to 1.2.5?

**Comment by pjona** [comment]
Yes

**Comment by RamonSmit** [comment]
Done :-)

**Comment by RomanBurunkov** [comment]
Hi @pjona,

I've tested `add` method and found out one issue when adding item with parent_id.
When adding first children to parent with id parent_id, `add` method doesn't add expand/colapse buttons and further we have no chance to add then from user side. Looks like we should use setParent method which already exist. But I'm not quite sure where to add it.

**Comment by pjona** [comment]
@RomanBurunkov you are right, I will try to fix it. Can you create a issue with it?

**Comment by RomanBurunkov** [comment]
@pjona,

Issue 66 has been added  ;)

Thanks, Roman.

**Pull request merged**
